AWSTemplateFormatVersion: 2010-09-09
Description: Codified Config Rules
Parameters:
  Ec2VolumeTagKey:
    Type: String
    Default: CostCenter

Resources:

  ConfigRuleForVolumeTags:
    Type: AWS::Config::ConfigRule
    Properties:
      InputParameters:
        tag1Key: CostCenter
      Scope:
        ComplianceResourceTypes:
          - AWS::EC2::Volume
      Source:
        Owner: AWS
        SourceIdentifier: REQUIRED_TAGS
